---
version: "2.1"
services:
  target-server-01:
    image: ghcr.io/linuxserver/openssh-server:8.4_p1-r3-ls49
    container_name: target-server-01
    hostname: target-server-01 #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
      - PUBLIC_KEY=${PUBLIC_KEY} #optional
      - PUBLIC_KEY_FILE=/path/to/file #optional
      - PUBLIC_KEY_DIR=/path/to/directory/containing/_only_/pubkeys #optional
      - SUDO_ACCESS=true #optional
      - USER_NAME=hoge #optional
    volumes:
      - ./container-files:/container-files
    ports:
      - 2222:2222
      - 8082:80
    restart: unless-stopped
  target-server-02:
    image: ghcr.io/linuxserver/openssh-server:8.4_p1-r3-ls49
    container_name: target-server-02
    hostname: target-server-02 #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
      - PUBLIC_KEY=${PUBLIC_KEY} #optional
      - PUBLIC_KEY_FILE=/path/to/file #optional
      - PUBLIC_KEY_DIR=/path/to/directory/containing/_only_/pubkeys #optional
      - SUDO_ACCESS=true #optional
      - USER_NAME=foo #optional
    volumes:
      - ./container-files:/container-files
    ports:
      - 2223:2222
      - 8083:80
    restart: unless-stopped
  target-server-03:
    image: ghcr.io/linuxserver/openssh-server:8.4_p1-r3-ls49
    container_name: target-server-03
    hostname: target-server-03 #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
      - PUBLIC_KEY=${PUBLIC_KEY} #optional
      - PUBLIC_KEY_FILE=/path/to/file #optional
      - PUBLIC_KEY_DIR=/path/to/directory/containing/_only_/pubkeys #optional
      - SUDO_ACCESS=true #optional
      - USER_NAME=john #optional
    volumes:
      - ./container-files:/container-files
    ports:
      - 2224:2222
      - 8084:80
    restart: unless-stopped
